# Generated by Django 4.2.1 on 2023-05-30 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.BigAutoField(
                        default=0, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=256, unique=True),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=64, null=True)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("photo", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("W", "Робітник"),
                            ("E", "Роботодавець"),
                            ("S", "Суперкористувач"),
                        ],
                        default="W",
                        max_length=1,
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        choices=[
                            ("E", "Дошкільна"),
                            ("D", "Повна загальна середня"),
                            ("C", "Професійна"),
                            ("B", "Фахова передвища"),
                            ("A", "Вища"),
                        ],
                        max_length=1,
                    ),
                ),
                ("profession", models.CharField(max_length=64)),
                ("end_of_education", models.DateField()),
                ("skills", models.CharField(max_length=256)),
                ("city", models.CharField(max_length=64)),
                ("views", models.TextField(default="")),
                ("user_id", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_time", models.DateTimeField(auto_created=True)),
                ("title", models.CharField(max_length=128)),
                ("city", models.CharField(max_length=64)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("R", "Дистанційна"),
                            ("F", "Повна зайнятість"),
                            ("P", "Часткова зайнятість"),
                            ("N", "Фріланс"),
                        ],
                        max_length=1,
                    ),
                ),
                ("looking_for", models.CharField(default="Unknown", max_length=32)),
                ("description", models.TextField()),
                ("thumbnail", models.CharField(blank=True, max_length=512, null=True)),
                ("publisher", models.EmailField(max_length=254)),
                (
                    "candidates",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Vacancy",
                "verbose_name_plural": "Vacancies",
            },
        ),
    ]
